import { Users } from "lucide-react";
import { defineEntity } from "@/core/schema/types";
import { PendingSignups } from "./PendingSignups";

export const STAFF_ROLES = ["owner", "manager", "hr", "accounts", "finance", "marketing", "staff"] as const;

export const staff = defineEntity({
  name: "staff",
  label: "Staff",
  labelSingular: "Staff member",
  icon: Users,
  table: "staff",
  teams: ["hr"],
  unitField: "business_unit_id",
  titleField: "name",
  searchFields: ["name", "phone", "designation"],
  defaultSort: { field: "name", dir: "asc" },
  permissions: { create: ["owner", "manager", "hr"], update: ["owner", "manager", "hr"], delete: ["owner"] },
  listExtra: PendingSignups,
  fields: [
    { name: "name", label: "Name", type: "text", required: true },
    { name: "phone", label: "Phone", type: "phone" },
    { name: "email", label: "Email", type: "email", help: "Same email as their app login (shared mode)" },
    { name: "role", label: "Role", type: "select", options: STAFF_ROLES, required: true, default: "staff" },
    { name: "business_unit_id", label: "Business unit", type: "relation", entity: "business-units", required: true },
    { name: "designation", label: "Designation", type: "text", placeholder: "Front office, Chef…" },
    { name: "active", label: "Active", type: "boolean", default: true, help: "Currently employed" },
    { name: "joined_on", label: "Joined on", type: "date" },
    { name: "left_on", label: "Left on", type: "date" },
    { name: "salary", label: "Salary (monthly)", type: "money", min: 0 },
    { name: "auth_user_id", label: "Login user id", type: "text", help: "Supabase Auth user id (shared mode). Leave blank in local mode." },
    { name: "notes", label: "Notes", type: "textarea" },
    { name: "shift1_start", label: "Shift 1 starts", type: "text", default: "07:00", placeholder: "07:00" },
    { name: "shift1_end", label: "Shift 1 ends", type: "text", default: "13:00", placeholder: "13:00" },
    { name: "shift2_start", label: "Shift 2 starts", type: "text", default: "15:00", placeholder: "15:00" },
    { name: "shift2_end", label: "Shift 2 ends", type: "text", default: "22:00", placeholder: "22:00" },
    { name: "daily_routine", label: "Daily routine (task sheet)", type: "textarea", help: "One line per job, start with the time — shown every day on their task sheet", placeholder: "07:00 Pool and lawn check\n08:00 Breakfast service\n11:00 Rooms ready for check-in\n15:00 Evening setup\n19:00 Dinner service" },
    { name: "job_description", label: "Job description", type: "textarea", help: "Shown to the staff member on My Day → My role", placeholder: "What this person is responsible for, day to day" },
    { name: "kpi_1", label: "KPI 1", type: "text", placeholder: "e.g. Answer every lead within 30 minutes" },
    { name: "kpi_2", label: "KPI 2", type: "text", placeholder: "e.g. Occupancy ≥ 70% this month" },
    { name: "kpi_3", label: "KPI 3", type: "text", placeholder: "e.g. Guest rating ≥ 4.5" },
    { name: "kpi_4", label: "KPI 4", type: "text", placeholder: "e.g. Zero overdue tasks" },
    { name: "kpi_5", label: "KPI 5", type: "text", placeholder: "e.g. Daily report sent by 9 am" },
    { name: "kra_1", label: "KRA 1", type: "text", placeholder: "e.g. Reservations & lead follow-up" },
    { name: "kra_2", label: "KRA 2", type: "text", placeholder: "e.g. Guest experience" },
    { name: "kra_3", label: "KRA 3", type: "text", placeholder: "e.g. Housekeeping standards" },
    { name: "kra_4", label: "KRA 4", type: "text", placeholder: "e.g. Cost control" },
    { name: "kra_5", label: "KRA 5", type: "text", placeholder: "e.g. Team coordination" },
  ],
  listColumns: ["name", "role", "business_unit_id", "designation", "phone", "active"],
  reverse: [
    { entity: "attendance", field: "staff_id", label: "Attendance" },
    { entity: "tasks", field: "assigned_to", label: "Tasks" },
    { entity: "tickets", field: "assigned_to", label: "Tickets" },
    { entity: "leads", field: "assigned_to", label: "Leads" },
  ],
});
