-- JD One network: Area help (thana, hospitals, fire, complaint lines) per area. Safe to re-run.
create table if not exists jdone.area_services (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'Police station',
  name text not null,
  area_covered text,
  address text,
  state text not null default 'Rajasthan',
  district text not null default 'Udaipur',
  city text not null,
  lat double precision,
  lng double precision,
  phone text,
  phone2 text,
  hours text default '24x7',
  officer_name text,
  officer_rank text,
  officer_phone text,
  beat_officer text,
  beat_rank text,
  beat_area text,
  beat_phone text,
  officers_checked_on date,
  verified boolean not null default false,
  source_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references jdone.staff(id) on delete set null
);
create index if not exists area_services_geo_idx on jdone.area_services (state, district, city, type);

drop trigger if exists set_updated_at on jdone.area_services;
create trigger set_updated_at before update on jdone.area_services for each row execute function jdone.set_updated_at();
alter table jdone.area_services enable row level security;
drop policy if exists "staff read" on jdone.area_services;
create policy "staff read" on jdone.area_services for select to authenticated using (jdone.is_staff());
drop policy if exists "staff insert" on jdone.area_services;
create policy "staff insert" on jdone.area_services for insert to authenticated with check (jdone.is_staff());
drop policy if exists "staff update" on jdone.area_services;
create policy "staff update" on jdone.area_services for update to authenticated using (jdone.is_staff()) with check (jdone.is_staff());
drop policy if exists "owner delete" on jdone.area_services;
create policy "owner delete" on jdone.area_services for delete to authenticated using (jdone.is_owner());
grant select, insert, update, delete on jdone.area_services to authenticated;

-- Seed: Udaipur area help (institutional numbers from public sources, researched 10 Oct 2026; verify before relying on them)
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Hiranmagri Police Station (City East circle)','Hiran Magri sectors (5/6/14 etc.), Tiger Hills, LAKADWAS (Patrika 13 Sep 2026: ''हिरणमगरी थाना क्षेत्र में लकड़वास''), Kalarwas RIICO; some parts may move to proposed Ayad thana','Hiran Magri Main Road, Sector 6, Udaipur 313002','Rajasthan','Udaipur','Udaipur','0294-2466757','8764527504 (CUG per sarkaricard)','24x7','https://www.patrika.com/udaipur-news/udaipur-woman-attack-9th-floor-20904736 | https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high (phone); Lakadwas jurisdiction medium-high (news-based); coordinates approximate',24.5590,73.7225,false where not exists (select 1 from jdone.area_services where name='Hiranmagri Police Station (City East circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Pratap Nagar Police Station (City East circle)','Pratap Nagar, Sundarwas/Oswal Nagar, Pratapnagar bypass/chauraha, Debari T-point & Debari area (news)','Pratap Nagar, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2490499',null,'24x7','https://udaipurblog.com/numbers | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR | https://www.patrika.com/udaipur-news/flyover-construction-work-at-pratapnagar-bypass-after-many-deaths-4678646','Confidence: high (phone); area medium; coordinates approximate',24.5980,73.7400,false where not exists (select 1 from jdone.area_services where name='Pratap Nagar Police Station (City East circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Savina Police Station (City East circle)','Savina, Sector 11 area, Savina Kheda (news)','Savina, Udaipur 313002','Rajasthan','Udaipur','Udaipur','0294-2484601','9530435181 (CUG per sarkaricard)','24x7','https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/ | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium; coordinates approximate',24.5480,73.7030,false where not exists (select 1 from jdone.area_services where name='Savina Police Station (City East circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Bhupalpura (Bhopalpura) Police Station (City East circle)','Bhupalpura, New Bhupalpura, Shobhagpura, Ayad chowki area (Ayad thana announced Feb 2026, land being acquired, not yet operational)','Bhupalpura, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2414102','8764855361 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/ | https://udaipurtimes.com/administration/udaipur-two-new-police-stations-ayad-mamer/cid18237906.htm','Confidence: high; coordinates approximate',24.5960,73.7080,false where not exists (select 1 from jdone.area_services where name='Bhupalpura (Bhopalpura) Police Station (City East circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Surajpole Police Station (City East circle)','Surajpole, old city east','Surajpole, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2411797','9530434853 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.5800,73.6960,false where not exists (select 1 from jdone.area_services where name='Surajpole Police Station (City East circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Hathipole Police Station (City West circle)','Hathipole, old city north','Hathipole, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2427073','9530434950 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.5880,73.6880,false where not exists (select 1 from jdone.area_services where name='Hathipole Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Dhan Mandi Police Station (City West circle)','Dhan Mandi, old city','Dhan Mandi, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2412941','9530435046 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.5800,73.6870,false where not exists (select 1 from jdone.area_services where name='Dhan Mandi Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Ghanta Ghar (Clock Tower) Police Station (City West circle)','Ghanta Ghar, Jagdish Chowk area, old city','Ghanta Ghar, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2411942','9530435249 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.5790,73.6860,false where not exists (select 1 from jdone.area_services where name='Ghanta Ghar (Clock Tower) Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Ambamata Police Station (City West circle)','Ambamata, Fateh Sagar west side','Ambamata, Udaipur 313004','Rajasthan','Udaipur','Udaipur','0294-2430488','9530435204 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.5930,73.6700,false where not exists (select 1 from jdone.area_services where name='Ambamata Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Sukher Police Station (City West circle)','Sukher, RIICO Sukher, north city','Sukher, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2441381','9530435335 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/','Confidence: high; coordinates approximate',24.6350,73.7180,false where not exists (select 1 from jdone.area_services where name='Sukher Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Badgaon Police Station (City West circle)','Badgaon/Bargaon area','Badgaon, Udaipur','Rajasthan','Udaipur','Udaipur','0294-2451486',null,'24x7','https://udaipurblog.com/numbers | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium; coordinates approximate',24.6230,73.6800,false where not exists (select 1 from jdone.area_services where name='Badgaon Police Station (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Women police station','Mahila Thana Udaipur (City West circle)','District-wide crimes against women','Udaipur city','Rajasthan','Udaipur','Udaipur','0294-2803727',null,'24x7','https://udaipurblog.com/numbers | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium (landline from older listing)',null,null,false where not exists (select 1 from jdone.area_services where name='Mahila Thana Udaipur (City West circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Paryatan (Tourist) Police Station','Tourist areas of Udaipur city','Old city, Udaipur','Rajasthan','Udaipur','Udaipur','0294-2425242',null,'24x7','https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium; coordinates approximate',24.5780,73.6840,false where not exists (select 1 from jdone.area_services where name='Paryatan (Tourist) Police Station' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Cyber police station','Cyber Police Station Udaipur','Udaipur district cyber crime','Udaipur (address not found in public sources)','Rajasthan','Udaipur','Udaipur','1930 (national cyber helpline)',null,'24x7 (helpline)','https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no | https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: medium (station landline not found)',null,null,false where not exists (select 1 from jdone.area_services where name='Cyber Police Station Udaipur' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Goverdhan Vilas (Gordhan Vilas) Police Station (Girwa circle)','Goverdhan Vilas, southern city edge','Goverdhan Vilas, Udaipur','Rajasthan','Udaipur','Udaipur','0294-2640050','9530435339 (CUG per sarkaricard)','24x7','https://udaipurblog.com/numbers | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/ | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: high; coordinates approximate',24.5450,73.6840,false where not exists (select 1 from jdone.area_services where name='Goverdhan Vilas (Gordhan Vilas) Police Station (Girwa circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Kurawad (Kurabad) Police Station (Girwa circle)','Kurabad and villages SE of Udai Sagar','Kurabad, Girwa, Udaipur','Rajasthan','Udaipur','Girwa','0294-2392721','9530435454 (CUG per sarkaricard)','24x7','https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no | https://sarkaricard.in/udaipur-police-station-list-cug-mobile-number/ | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium; coordinates approximate',24.4300,73.9300,false where not exists (select 1 from jdone.area_services where name='Kurawad (Kurabad) Police Station (Girwa circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Nai Police Station (Girwa circle)','Nai and villages west of city','Nai, Girwa, Udaipur','Rajasthan','Udaipur','Girwa','0294-2762228',null,'24x7','https://udaipurblog.com/numbers | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium; coordinates approximate',24.5300,73.6000,false where not exists (select 1 from jdone.area_services where name='Nai Police Station (Girwa circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Tidi Police Station (Girwa circle)','Tidi and villages south','Tidi, Girwa, Udaipur','Rajasthan','Udaipur','Girwa',null,null,'24x7','https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR','Confidence: medium (no official phone found); coordinates approximate',24.3700,73.8300,false where not exists (select 1 from jdone.area_services where name='Tidi Police Station (Girwa circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Dabok Police Station (Mavli circle)','Dabok, airport area, Dabok-road villages north of Udai Sagar','Dabok, Udaipur (near Maharana Pratap Airport)','Rajasthan','Udaipur','Girwa','0294-2655316',null,'24x7','https://udaipurblog.com/numbers | https://www.police.rajasthan.gov.in/old/PoliceStationWiseCLG.aspx?DistrictIdCLG=36&District=UDAIPUR | https://udaipurtimes.com/crime/dabok-police-station-action-5-accused-arrested-in-just-6/cid19200562.htm','Confidence: high; coordinates approximate',24.6200,73.8800,false where not exists (select 1 from jdone.area_services where name='Dabok Police Station (Mavli circle)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police station','Debari police post (chowki)','Debari (separate line in older directory; likely a chowki)','Debari, Udaipur','Rajasthan','Udaipur','Girwa','0294-2655948',null,'24x7','https://udaipurblog.com/numbers','Confidence: low; coordinates approximate',24.6000,73.8200,false where not exists (select 1 from jdone.area_services where name='Debari police post (chowki)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police control room','Udaipur Police Control Room','Udaipur district','SP Office, Udaipur','Rajasthan','Udaipur','Udaipur','112 / 100','0294-2414600','24x7','https://udaipurblog.com/numbers | https://udaipurtimes.com/uncategorized/udaipurs-important-helpline-numbers/c74416-w2859-cid135723-s10812.htm','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Udaipur Police Control Room' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police control room','Udaipur Police Control Room (mobile line)','Udaipur district','SP Office, Udaipur','Rajasthan','Udaipur','Udaipur','8764854787',null,'24x7','https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='Udaipur Police Control Room (mobile line)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Traffic police','Udaipur Traffic Control Room','Udaipur city','Udaipur','Rajasthan','Udaipur','Udaipur','0294-2484553','1095 (traffic helpline)','24x7','https://udaipurblog.com/numbers | https://www.indiacustomercare.com/udaipur-district-police-rajasthan-contact-no','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='Udaipur Traffic Control Room' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','SP Office Udaipur (office line)','Udaipur district','Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2413949',null,'Office hours','https://udaipurtimes.com/uncategorized/udaipurs-important-helpline-numbers/c74416-w2859-cid135723-s10812.htm','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='SP Office Udaipur (office line)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police control room','Emergency Response (ERSS) - police/fire/ambulance','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','112',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Emergency Response (ERSS) - police/fire/ambulance' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Police control room','Police','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','100',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Police' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Fire station','Fire brigade','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','101',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Fire brigade' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Ambulance','108 Emergency ambulance','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','108',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='108 Emergency ambulance' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Ambulance','102 Ambulance (maternal & child / Janani)','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','102',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='102 Ambulance (maternal & child / Janani)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','104 Health helpline (medical advice)','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','104',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='104 Health helpline (medical advice)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Women police station','Rajasthan Police Women Helpline','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','1090',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Rajasthan Police Women Helpline' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Cyber police station','Cyber fraud helpline (NCRP)','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','1930',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Cyber fraud helpline (NCRP)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','Childline','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','1098',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Childline' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','Rajasthan Sampark (CM grievance helpline)','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','181',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Rajasthan Sampark (CM grievance helpline)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','Senior citizen helpline','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','14567',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='Senior citizen helpline' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','ACB Rajasthan (anti-corruption)','Rajasthan','Rajasthan (state-wide)','Rajasthan','Udaipur','Udaipur','1064',null,'24x7','https://x.com/PoliceRajasthan/status/1985292067715624962','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='ACB Rajasthan (anti-corruption)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','Maharana Bhupal (MB) Govt Hospital / RNT Medical College hospitals',null,'Hospital Road, near Chetak Circle, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2528811','0294-2419100','24x7 casualty','https://udaipurblog.com/numbers | https://prognohealth.com/blog/list-of-government-hospitals-in-udaipur/','Confidence: medium; coordinates approximate',24.5890,73.6990,false where not exists (select 1 from jdone.area_services where name='Maharana Bhupal (MB) Govt Hospital / RNT Medical College hospitals' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','Zanana (Women''s) Hospital, RNT',null,'RNT campus, Udaipur','Rajasthan','Udaipur','Udaipur','0294-2523989',null,'24x7','https://udaipurblog.com/numbers','Confidence: low (old listing); coordinates approximate',24.5890,73.6990,false where not exists (select 1 from jdone.area_services where name='Zanana (Women''s) Hospital, RNT' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','Satellite Hospital Hiran Magri Sector 6',null,'Satellite Hospital Rd, Sector 6, Hiran Magri, Udaipur 313002','Rajasthan','Udaipur','Udaipur',null,null,'24x7 emergency (verify)','https://udaipurtimes.com/health-news/udaipur-gets-new-satellite-hospital/cid12296910.htm','Confidence: medium (no phone found)',24.5591,73.7222,false where not exists (select 1 from jdone.area_services where name='Satellite Hospital Hiran Magri Sector 6' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','Satellite Hospital Ambamata',null,'Ambamata, Udaipur','Rajasthan','Udaipur','Udaipur',null,null,null,'https://udaipurtimes.com/health-news/udaipur-gets-new-satellite-hospital/cid12296910.htm','Confidence: medium (no phone found); coordinates approximate',24.5940,73.6680,false where not exists (select 1 from jdone.area_services where name='Satellite Hospital Ambamata' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','Satellite Hospital Bargaon (Badgaon)',null,'Badgaon, Udaipur','Rajasthan','Udaipur','Udaipur',null,null,null,'https://udaipurtimes.com/health-news/udaipur-gets-new-satellite-hospital/cid12296910.htm','Confidence: medium (no phone found); coordinates approximate',24.6250,73.6850,false where not exists (select 1 from jdone.area_services where name='Satellite Hospital Bargaon (Badgaon)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (govt)','PHC Lakadwas','Lakadwas gram panchayat','Lakadwas, Girwa, Udaipur 313003','Rajasthan','Udaipur','Girwa',null,null,'Day OPD (verify)','https://irationcard.com/udaipur-districts-government/ | https://indiamapia.com/Udaipur/Lakadwas.html','Confidence: medium (no phone found); coordinates approximate',24.5505,73.8073,false where not exists (select 1 from jdone.area_services where name='PHC Lakadwas' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','PIMS - Pacific Institute of Medical Sciences, Umarda (nearest large hospital to Lakadwas)',null,'Ambua Road, Village Umarda, Udaipur 313015','Rajasthan','Udaipur','Girwa','0294-3510000','8696440666','24x7','https://www.pacificmedicalsciences.ac.in/contact-us/','Confidence: medium; coordinates approximate',24.5650,73.8100,false where not exists (select 1 from jdone.area_services where name='PIMS - Pacific Institute of Medical Sciences, Umarda (nearest large hospital to Lakadwas)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','Geetanjali Medical College & Hospital',null,'Hiranmagri Extn, Manwakhera, NH-8 Bypass near Eklingpura Chouraha, Udaipur 313002','Rajasthan','Udaipur','Udaipur','8003098718 (24x7 emergency)','0294-2500000','24x7','https://www.geetanjalihospital.co.in/service/emergency','Confidence: high; coordinates approximate',24.5370,73.7470,false where not exists (select 1 from jdone.area_services where name='Geetanjali Medical College & Hospital' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','Paras Health Udaipur (Paras JK)',null,'Plot 1, JK Lane, Shobhagpura, Udaipur 313001','Rajasthan','Udaipur','Udaipur','9091790917 (emergency)','8080808069','24x7','https://www.parashospitals.com/udaipur','Confidence: high; coordinates approximate',24.6130,73.7130,false where not exists (select 1 from jdone.area_services where name='Paras Health Udaipur (Paras JK)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','Pacific Medical College & Hospital (PMCH), Bhilon ka Bedla',null,'Bhilon ka Bedla, Pratappura, NH-27, Girwa, Udaipur 313024','Rajasthan','Udaipur','Girwa','0294-3920000','7230045361','24x7','https://www.pacificmedical.ac.in/Contact.aspx','Confidence: medium; coordinates approximate',24.6510,73.7330,false where not exists (select 1 from jdone.area_services where name='Pacific Medical College & Hospital (PMCH), Bhilon ka Bedla' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','GBH American Hospital',null,'101 Kothi Bagh, Bhatt Ji Ki Bari, Meera Girls College Rd, Udaipur 313001','Rajasthan','Udaipur','Udaipur','9352304050 (emergency)','0294-3535000','24x7','https://www.gbhamericanhospital.com/contactus.php','Confidence: medium; coordinates approximate',24.5870,73.6950,false where not exists (select 1 from jdone.area_services where name='GBH American Hospital' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Hospital (private, 24x7 emergency)','Aravali Hospital',null,'332 Ambamata Scheme, Udaipur 313004','Rajasthan','Udaipur','Udaipur','9352108108 (emergency/ambulance)',null,'24x7','https://aravalihospital.in/contact-us/','Confidence: medium; coordinates approximate',24.5930,73.6710,false where not exists (select 1 from jdone.area_services where name='Aravali Hospital' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Fire station','Udaipur Nagar Nigam Fire Station (main)','Udaipur city','Opp. Bhupalpura Police Station, Udaipur 313001','Rajasthan','Udaipur','Udaipur','101','0294-2525390','24x7','https://udaipurblog.com/numbers | https://www.justdial.com/Udaipur-Rajasthan/Fire-Station-Opposite-Gopalpura-Police-Station-Udaipur-City/9999PX294-X294-121116124156-D4B5_BZDET','Confidence: medium; coordinates approximate',24.5960,73.7085,false where not exists (select 1 from jdone.area_services where name='Udaipur Nagar Nigam Fire Station (main)' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Electricity complaint','AVVNL (Ajmer Discom) - no supply / fault complaint','Udaipur district','AVVNL (covers Udaipur)','Rajasthan','Udaipur','Udaipur','1912','1800-180-6565','24x7','https://jansoochna.rajasthan.gov.in/Images/ClickablePdf/202009091100118854.pdf','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='AVVNL (Ajmer Discom) - no supply / fault complaint' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Electricity complaint','AVVNL WhatsApp/SMS complaints','Udaipur district',null,'Rajasthan','Udaipur','Udaipur','9414000783 (WhatsApp/SMS)',null,'24x7','https://jansoochna.rajasthan.gov.in/Images/ClickablePdf/202009091100118854.pdf','Confidence: high',null,null,false where not exists (select 1 from jdone.area_services where name='AVVNL WhatsApp/SMS complaints' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Water complaint','PHED Udaipur water-supply complaints','Udaipur city','PHED office, Udaipur','Rajasthan','Udaipur','Udaipur','1800-180-6088','0294-2481540','Office/control room','https://udaipurtimes.com/administration/toll-free-number-for-watersupply-related-complaints/c74416-w2859-cid113326-s10702.htm','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='PHED Udaipur water-supply complaints' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Water complaint','PHED Rajasthan state helpline','Rajasthan',null,'Rajasthan','Udaipur','Udaipur','1800-180-6222',null,'24x7','https://www.bajajfinserv.in/rajasthan-phed-water-bill-customer-care','Confidence: medium',null,null,false where not exists (select 1 from jdone.area_services where name='PHED Rajasthan state helpline' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Municipal office','Udaipur Municipal Corporation (Nagar Nigam) helpline','Udaipur city wards (Lakadwas village is a gram panchayat, outside UMC)','Town Hall Link Road, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2426262','0294-2421255 (Commissioner office)','Office hours','https://udaipurmc.org/pages/contactus','Confidence: high; coordinates approximate',24.5830,73.6920,false where not exists (select 1 from jdone.area_services where name='Udaipur Municipal Corporation (Nagar Nigam) helpline' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Collectorate','District Collectorate Udaipur','Udaipur district','Collectorate Road, Shakti Nagar, Udaipur 313001','Rajasthan','Udaipur','Udaipur','0294-2410408',null,'Office hours','https://helpcustomercare.in/udaipur-district-number/','Confidence: medium; coordinates approximate',24.5900,73.7020,false where not exists (select 1 from jdone.area_services where name='District Collectorate Udaipur' and district='Udaipur');
insert into jdone.area_services (type,name,area_covered,address,state,district,city,phone,phone2,hours,source_url,notes,lat,lng,verified) select 'Other','Disaster management helpline','Rajasthan',null,'Rajasthan','Udaipur','Udaipur','1077',null,'24x7 (monsoon)','https://helpcustomercare.in/udaipur-district-number/','Confidence: low',null,null,false where not exists (select 1 from jdone.area_services where name='Disaster management helpline' and district='Udaipur');
